-- Slice 7: in-app notifications. A thin event log of things a dealer would want to know
-- about but may not be looking at: they were outbid, they won, their listing sold. Rows are
-- generated inside the existing writer RPCs (place_bid / close_auction / buy_now_listing) —
-- see the create-or-replace block appended below. "Ending soon" is derived on-read from the
-- watchlist (no rows here).

create table notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_dealer_id uuid not null references dealers(id),
  type text not null check (type in ('outbid','won','sold')),
  auction_id uuid not null references auctions(id),
  created_at timestamptz not null default now(),
  read_at timestamptz            -- null = unread
);
create index on notifications (recipient_dealer_id, created_at desc);

-- Reads are dealer-scoped in the query (same no-RLS demo trust model as auctions/bids).
-- Only the SECURITY DEFINER writers (running as owner) and service_role (tests) write rows.
grant select on notifications to anon, authenticated;
grant select, insert, update, delete on notifications to service_role;

-- Internal helper: insert one notification. Only ever called from within the SECURITY DEFINER
-- writers (which run as owner and always retain execute), so its default PUBLIC execute grant
-- is revoked — no external caller can forge a row (and anon has no INSERT on the table anyway).
create or replace function _notify(p_recipient uuid, p_type text, p_auction uuid)
returns void language sql as $$
  insert into notifications (recipient_dealer_id, type, auction_id)
  values (p_recipient, p_type, p_auction);
$$;
revoke execute on function _notify(uuid, text, uuid) from public, anon, authenticated;

-- Mark all of a dealer's unread notifications read. Writer: service_role-only (the browser
-- anon key must never reach it); dealer identity comes from the httpOnly cookie in the action.
create or replace function mark_notifications_read(p_dealer_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  update notifications set read_at = now()
   where recipient_dealer_id = p_dealer_id and read_at is null;
end;
$$;
revoke execute on function mark_notifications_read(uuid) from public, anon, authenticated;
grant execute on function mark_notifications_read(uuid) to service_role;

-- Redefine test_reset to also clear notifications so integration tests stay isolated (a
-- notification generated by one test must not leak into the next). Preserves the 0006 change
-- that scopes the auction reset to non-draft rows (drafts keep their identity across resets).
create or replace function test_reset() returns void language plpgsql security definer as $$
begin
  truncate bids restart identity cascade;
  truncate settlements restart identity cascade;
  truncate notifications restart identity cascade;
  update auctions
    set current_bid = null,
        current_winner_dealer_id = null,
        status = 'live',
        end_time = now() + interval '2 hours'
  where status <> 'draft';
end;
$$;
